"""Lead: analyse every remaining exact-match failure between v1 and v2 to find
normalization gaps that could break cross-version fingerprint matching.

v2 was generated by re-inserting text with a different font, so it is the perfect
adversarial sample for Unicode variant drift.
"""
import os
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.stdout.reconfigure(encoding="utf-8")

from core import db as cdb, store, fingerprint as fp  # noqa: E402

con = cdb.connect()
v1 = store.segments_of_version(con, 1)
v2 = store.segments_of_version(con, 2)
v1 = [s for s in v1 if s["role"] == "body"]
v2 = [s for s in v2 if s["role"] == "body"]
print(f"v1 body={len(v1)}  v2 body={len(v2)}")

idx1 = {}
for s in v1:
    idx1.setdefault(s["fingerprint"], []).append(s)
idx2 = {}
for s in v2:
    idx2.setdefault(s["fingerprint"], []).append(s)

only1 = set(idx1) - set(idx2)
only2 = set(idx2) - set(idx1)
print(f"fingerprints only in v1: {len(only1)}   only in v2: {len(only2)}")

# For each unmatched v1 fp, find its best counterpart in v2 by ratio.
unmatched2 = [s for k in only2 for s in idx2[k]]
unmatched1 = [s for k in only1 for s in idx1[k]]
print(f"unmatched segments: v1={len(unmatched1)} v2={len(unmatched2)}\n")

# Report which chars differ
char_pairs = Counter()
for s1 in unmatched1:
    best, bestr = None, 0.0
    for s2 in unmatched2:
        r = fp.ratio(s1["canonical_text"], s2["canonical_text"])
        if r > bestr:
            best, bestr = s2, r
    if best is None or bestr < 0.9:
        print(f"HIGH-DIVERGENCE ratio={bestr:.3f} v1={s1['text'][:90]!r}")
        if best:
            print(f"{'':36s} v2={best['text'][:90]!r}")
        continue
    a, b = fp.normalize(s1["canonical_text"]), fp.normalize(best["canonical_text"])
    for ca, cb in zip(a, b):
        if ca != cb:
            char_pairs[(ca, cb)] += 1
    print(f"ratio={bestr:.4f} v1={a[:80]!r}")
    print(f"{'':16s} v2={b[:80]!r}")

print("\n=== differing character pairs (norm_a -> norm_b) ===")
for (ca, cb), n in char_pairs.most_common(40):
    print(f"  {ca!r} U+{ord(ca):04X} -> {cb!r} U+{ord(cb):04X}   x{n}")

# Count all unusual chars present anywhere in v1 vs v2
def charset(rows):
    c = Counter()
    for r in rows:
        for ch in r["text"]:
            if ord(ch) > 127:
                c[ch] += 1
    return c

c1, c2 = charset(v1), charset(v2)
print("\n=== non-ASCII in v1 not (or rarely) in v2 ===")
for ch, n in c1.most_common(40):
    if c2.get(ch, 0) == 0:
        print(f"  v1 {ch!r} U+{ord(ch):04X} x{n}  -> absent in v2")
print("\n=== non-ASCII in v2 not in v1 ===")
for ch, n in c2.most_common(40):
    if c1.get(ch, 0) == 0:
        print(f"  v2 {ch!r} U+{ord(ch):04X} x{n}  -> absent in v1")
con.close()
